# Generated by Django 3.0 on 2020-08-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegecourses',
            options={'verbose_name': 'College Course'},
        ),
    ]
