# Generated by Django 3.0 on 2020-08-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200812_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collegeCourses',
            new_name='collegeCourse',
        ),
    ]
